hash-format = "sha256"

[[files]]
file = ".github/ISSUE_TEMPLATE/feature_request.yml"
hash = "42e1ab77289fa80cbfd776c92d0fb0f12210fea08d0980e606c9cc5c4359e25a"

[[files]]
file = ".github/ISSUE_TEMPLATE/modpack_bug.yml"
hash = "0351af37d8ebfd114ff8aa134defc5478b3a60be32a61e0ed6cb6fa1891a6487"

[[files]]
file = ".github/ISSUE_TEMPLATE/pull_request_template.md"
hash = "04494eb2a829a2c2ad350aee9684def8f6e794f48a91abf0685160287c04fb2e"

[[files]]
file = ".github/workflows/syntax_check.yml"
hash = "163b59978745f2a1a42e16a524c02986d96e7ef0f4bb627e877a5848f63e9da5"

[[files]]
file = "README.md"
hash = "8d257ee1634e1134175e3a10ab28834828f6ac7abc5da3f3939a184e491bf7f7"
