name = "HonhuCraft"
author = "Yuzcen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "467d692472ffe50f8f40dced07212f20a52b2410f6c54c9bdc6ddd9e8602b83b"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
